<html>
	<body>
		<table>
			<tr>
				<td>
					<h3>New Bulletin Reply From $classname</h3>

					<b>Main Message</b>
					<div style="border:solid 1px #ccc;padding:20px;">
						$parent.message
					</div>
					<br/>
					<br/>
					<b>Reply</b>
					<div style="border:solid 1px #ccc;padding:20px;">
						$msg
						<br/>
						<br/>
						From: $sender.lastname, $sender.firstname
					</div>
					<br/>
					<br/>
					
					Thanks,<br><br>
					The Gazeebu Team
					
					<br>
					<br>
					<br>
					<a href="www.gazeebu.com">Click here</a> to enter Gazeebu.<br/>
					<i>This message is generated by Gazeebu. Please do not reply</i>
				</td>
			</tr>	
		</table>
	</body>
</html>